services:
  wijck.me:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wijck.me
    ports:
      - "6530:3000"
    networks:
      - caddy
networks:
  caddy:
    external: true